= Changelog
:source-highlighter: coderay
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning
endif::[]

== 1.5.0
- Added support of so called "stacked" effects. Before if during one transition two or more actions issued the same effect (effect with the same key) only the last one would be executed. Now all of them will be executed. The order of execution should be considered to be undetermined for now.

== 1.4.0
- Added ability for multiple interpreters to share the same isolated re-frame db part.

== 1.3.2
- Bugfixing release, in 1.3.1 state wasn't properly keywordized, deep states weren't taken into account

== 1.3.1
- Interpreter state is now (js->clj) converted with all the keys keywordized

== 1.3.0
- let-machine and let-machine-> macros are added
- fixed bug introduced in 1.2.0, guards DB isolation worked incorrectly, it associated entire interpreter data into :db cofx, whereas it should have associated just db part

== 1.2.0
- Activities support added
- Examples are switched to Bootstrap from Semantic UI

== 1.1.0
- Service to control other machines via re-frame co/effects included back (it was removed before 1.0.0 release)

== 1.0.0
- First stable release
