= re-state

image:https://img.shields.io/clojars/v/maximgb/re-state.svg[link=https://clojars.org/maximgb/re-state]
image:https://img.shields.io/badge/License-MIT-yellow.svg[link=https://raw.githubusercontent.com/MaximGB/re-restate/master/LICENSE]

Re-frame supplimentary library which routes dispatched events via statecharts implementing final state machines

== TL;DR

Re-state routes re-frame events via state chart interpreter, currently backed by https://xstate.js.org[XState] library,
thus allowing more fine grained event handling. A re-frame component might use a statechart interpreter to dispatch to and
handle events related only to the component. The library also implements facilities to isolate component state within re-frame
application database, thus making it possible to write real independent standalone components.

== Instalation

[source, clojure]
====
{:deps {org.clojure/clojure {:mvn/version "1.10.0"} ;; <1>
       org.clojure/clojurescript {:mvn/version "1.10.520"} ;; <2>
       reagent/reagent {:mvn/version "0.8.1"} ;; <3>
       re-frame/re-frame {:mvn/version "0.10.6"} ;; <4>
       maximgb.re-state {:mvn/version "0.4.0-SNAPSHOT"} <5>
====

<1>, <2>, <3>, <4>, <5> - Use up-to-date versions for your project here
